### ISSUE TITLE
个人资料点击绑定账号后报错

### ISSUE THREAD

**Issue by xiangchu95** [halo-sigs/plugin-oauth2#11]
![image](https://user-images.githubusercontent.com/110237853/229112620-1d1d6647-8d80-4656-b6d0-0654148f9e27.png)

**Comment by dormirr** [comment]
> 我也是。是哪里配置不对吗？

回调地址改为 http 可以解决。

**Comment by jkjoy** [comment]
> 

的确是改成http就可以了。但是这不是bug么

**Comment by leealu** [comment]
> > 我也是。是哪里配置不对吗？
> 
> 回调地址改为 http 可以解决。

在哪里改回调地址

**Comment by jkjoy** [comment]
> > > 我也是。是哪里配置不对吗？
> > 
> > 
> > 回调地址改为 http 可以解决。
> 
> 在哪里改回调地址

github

**Comment by jkjoy** [comment]
> > > > > 我也是。是哪里配置不对吗？
> > > > 
> > > > 
> > > > 回调地址改为 http 可以解决。
> > > 
> > > 
> > > 在哪里改回调地址
> > 
> > 
> > github
> 
> 具体怎么操作，谢谢，小白有点。。。

申请api key 的页面

**Comment by xiangchu95** [comment]
![image](https://user-images.githubusercontent.com/110237853/230034395-86d06900-be51-4278-8dc4-78e36f15bd91.png)
http 和https都用不了

**Comment by xiangchu95** [comment]
![image](https://user-images.githubusercontent.com/110237853/230034977-46449842-ac9b-48db-b405-6dc70bfa0906.png)

http 和htttps都用不了

**Comment by leealu** [comment]
> ![image](https://user-images.githubusercontent.com/110237853/230034977-46449842-ac9b-48db-b405-6dc70bfa0906.png)
> 
> http 和htttps都用不了

我也是一样的

**Comment by guqing** [comment]
> ![image](https://user-images.githubusercontent.com/110237853/230034977-46449842-ac9b-48db-b405-6dc70bfa0906.png)
> 
> http 和htttps都用不了

回调地址有问题，参考：
<img width="892" alt="image" src="https://user-images.githubusercontent.com/38999863/230392718-5b7f28c6-f033-4eaf-92eb-d1d66d217060.png">
https://github.com/halo-dev/halo/issues/3690#issuecomment-1499046034

**Comment by jkjoy** [comment]
你成功了？

**Comment by guqing** [comment]
> 你成功了？

一直都可以 不行的原因几乎都是回调地址填写有问题 注意是： `域名/login/oauth2/code/github` 不要填写为

**Comment by leealu** [comment]
> 你成功了？

https改为http，回调地址按照上面填写，我成功了，之前应该就是回调地址没写对，我们应该写的是登陆地址，注意对照一下

**Comment by jkjoy** [comment]
> 

不好意思,我就是按照文档填写的callback地址 还是错误

**Comment by leealu** [comment]
> > 
> 
> 不好意思,我就是按照文档填写的callback地址 还是错误

你的github配置图·还有你的后台配置图贴出来看看

**Comment by jkjoy** [comment]
> > > 
> > 
> > 
> > 不好意思,我就是按照文档填写的callback地址 还是错误
> 
> 你的github配置图·还有你的后台配置图贴出来看看

可能跟我使用了CDN有关吧

**Comment by dormirr** [comment]
> > 你成功了？
> 
> 一直都可以 不行的原因几乎都是回调地址填写有问题 注意是： `域名/login/oauth2/code/github` 不要填写为 /oauth2/authorization/github 如果使用了tls 且 nginx没有配置过 `proxy_set_header X-Forwarded-Proto $scheme;`则回调地址使用http 否则使用https 可以两个协议都试试

楼上说的正解。主要还是检查下 Nginx 配置和链接地址，还有问题可以贴出来 Nginx 配置和插件配置、GitHub 回调地址配置看看。另外大家可以注意下插件版本 1.0.2，halo 版本 2.4.2，我在这个版本使用是没问题的。

**Comment by leealu** [comment]
> > > 你成功了？
> > 
> > 
> > 一直都可以 不行的原因几乎都是回调地址填写有问题 注意是： `域名/login/oauth2/code/github` 不要填写为 /oauth2/authorization/github 如果使用了tls 且 nginx没有配置过 `proxy_set_header X-Forwarded-Proto $scheme;`则回调地址使用http 否则使用https 可以两个协议都试试
> 
> 楼上说的正解。主要还是检查下 Nginx 配置和链接地址，还有问题可以贴出来 Nginx 配置和插件配置、GitHub 回调地址配置看看。另外大家可以注意下插件版本 1.0.2，halo 版本 2.4.2，我在这个版本使用是没问题的。

我刚更新了2.4.2，又出了新问题，我是H2，现在直接成了新站，哈哈无语了

**Comment by dormirr** [comment]
> 

果然升级前还是要做好备份😀。我用的是 PostgreSQL 作为数据库，没什么问题。

**Comment by leealu** [comment]
> > 
> 
> 果然升级前还是要做好备份😀。我用的是 PostgreSQL 作为数据库，没什么问题。

H2的怎么恢复数据?

**Comment by jkjoy** [comment]
![image](https://user-images.githubusercontent.com/23159890/230705787-6da09f12-baba-4f6f-aa78-f687facee31a.png)

**Comment by jkjoy** [comment]
halo版本
[2.4.1](https://github.com/halo-dev/halo/releases/tag/v2.4.1)
插件版本 1.0.2

**Comment by JohnNiang** [comment]
2.4.2 已经修复了配置的 Authorization callback URL 不正确的问题。可参考：<https://github.com/halo-dev/halo/issues/3670>。

如果之前因为配置 https 无法正常工作而改成 http，升级到 2.4.2 可能需要更改回来。

**Comment by jkjoy** [comment]
> 

刚升级了2.4.2还是不行

**Comment by jkjoy** [comment]
而且我已经关闭了CDN.

**Comment by oliverwu-cn** [comment]
我也是把回调地址 https 改成 http 就绑定成功了，哈哈哈，虽然不懂原理，但是成功了
