### ISSUE TITLE
第三方登录自动被关闭

### ISSUE THREAD

**Issue by infanx** [halo-sigs/plugin-oauth2#13]
版本2.4.1
如图：
![image](https://user-images.githubusercontent.com/65985757/230024372-544d88a1-01f6-47f7-9e94-bbad3260710c.png)
![image](https://user-images.githubusercontent.com/65985757/230024114-e40d000e-545a-4849-8436-5afd4fa560a7.png)
docker部署没有重启过容器

**Comment by wxyShine** [comment]
相同问题+1  版本也一样 部署方式也一样

**Comment by ruibaby** [comment]
在最新的版本没有再收到过类似反馈，所以我将关闭此 issue，如果后续能够再稳定复现，可以重新提交 issue。

/close
