### ISSUE TITLE
出现400错误

### ISSUE THREAD

**Issue by maizi08** [halo-sigs/plugin-oauth2#14]
![image](https://user-images.githubusercontent.com/112745722/230054521-688d190e-7443-4c2b-ab28-bbf5504b3d9c.png)

**Comment by JohnNiang** [comment]
/kind bug

建议描述一下复现步骤，同时提供一下详细的错误日志。

**Comment by HimiCos** [comment]
到了`登陸並綁定`的步驟後，直到顯示`綁定成功`都沒問題。最後就會顯示`錯誤400`

https://user-images.githubusercontent.com/92566148/230717494-ed11c5cf-9f56-4002-ba0f-d8d1d28e6398.mp4

![CleanShot 2023-04-08 at 18 59 54@2x](https://user-images.githubusercontent.com/92566148/230717582-3f77d086-8f7a-4097-9949-2a1985a2e16d.png)

**Comment by homeqian** [comment]
这是因为你的github的Public profile没有设置自己的Name

https://github.com/settings/profile

**Comment by homeqian** [comment]
> 到了`登陸並綁定`的步驟後，直到顯示`綁定成功`都沒問題。最後就會顯示`錯誤400`
> 
>  CleanShot.2023-04-08.at.18.57.00-converted.mp4 
> ![CleanShot 2023-04-08 at 18 59 54@2x](https://user-images.githubusercontent.com/92566148/230717582-3f77d086-8f7a-4097-9949-2a1985a2e16d.png)

这是因为你的github的Public profile没有设置自己的Name

https://github.com/settings/profile

**Comment by bennyz327** [comment]
的確應該加到文档裡，花了一個下午找問題找到這邊才解決

**Comment by atangccc** [comment]
> > 到了的步驟後，直到顯示都沒問題。最後就會顯示`登陸並綁定``綁定成功``錯誤400`
> > CleanShot.2023-04-08.at.18.57.00-converted.mp4
> > ![CleanShot 2023-04-08在18：59 54@2x](https://user-images.githubusercontent.com/92566148/230717582-3f77d086-8f7a-4097-9949-2a1985a2e16d.png)
> 
> 这是因为你的github的Public profile没有设置自己的Name
> 
> https://github.com/settings/profile

![1722063571555](https://github.com/user-attachments/assets/cc768ce4-6c10-45e3-9531-96ff3f60ea9a)
如果是这个的话，好像没成功
