### ISSUE TITLE
第三方登录插件出现使用问题

### ISSUE THREAD

**Issue by wzry623090** [halo-sigs/plugin-oauth2#19]
点了启用插件，但是它上面还是显示插件没有启用，不知道什么原因，这回没有日志或者提示

**Comment by ruibaby** [comment]
1.0.2 的 Release Note 附带了解决方案：https://github.com/halo-sigs/plugin-oauth2/releases/tag/v1.0.2

问题原因：https://github.com/halo-dev/halo/issues/3720

/close
/kind support
