### ISSUE TITLE
第三方登录无效

### ISSUE THREAD

**Issue by Rainsiy** [halo-sigs/plugin-oauth2#20]
我在我自己的网站上安装插件后，尝试绑定GitHub账号，或者是用GitHub账号登录均无效。
连[Halo演示站](https://demo.halo.run/)，我目前用Chrome、Safari等浏览器测试均无法正常登陆。

我的配置如下：
Halo版本：[2.4.1](https://github.com/halo-dev/halo/releases/tag/v2.4.1)
OAuth Apps中Authorization callback URL设置为：https://域名.com/login/oauth2/code/github
OAuth Apps中Homepage URL设置为：https://域名.com
Halo中身份认证->GitHub(已启用)->设置->Client ID、Client Secret均正确。

选择GitHub登录后，无任何提示，目前仅看出来链接会从
https://demo.halo.run/console/#/login 变成⬇️
https://demo.halo.run/console/#/login?error
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/100349556/230724904-c4188c86-b08c-401f-962d-724ef0f59428.png">

**Comment by ruibaby** [comment]
demo.halo.run 是因为在升级到 2.4.2 之后没有修改回调地址的协议，目前三种方式都已经正常。如果你的网站目前还有问题，可以先检查一下是否有异常日志。

**Comment by cyril-cheng** [comment]
> demo.halo.run 是因为在升级到 2.4.2 之后没有修改回调地址的协议，目前三种方式都已经正常。如果你的网站目前还有问题，可以先检查一下是否有异常日志。

2.4.2，使用pandapro主题，绑定会显示http500错误。
