### ISSUE TITLE
扩展资源文件的 className 不正确

### ISSUE THREAD

**Issue by guqing** [halo-sigs/plugin-oauth2#25]
如 `className: run.halo.app.security.authentication.oauth2.Oauth2Authenticator` 正确的值应该是 `run.halo.oauth.Oauth2Authenticator`

起初是在 Halo 中实现转移到插件时忘记修改导致

/kind improvement
/assign

**Comment by ruibaby** [comment]
这会造成什么影响吗？

**Comment by guqing** [comment]
> 这会造成什么影响吗？

目前选取扩展时没有加校验，后续如果支持可以让用户选择让某些扩展生效功能时，如果这个 className 不正确就会不管用
