### ISSUE TITLE
安装这个插件以后一直报错

### ISSUE THREAD

**Issue by AbsoluteZeroKing** [halo-sigs/plugin-oauth2#27]
我之前的halo版本是2.1（应该是），误装了这个插件，然后就出现了后台各种问题，然后我用docker更新了一下halo，但是更新以后这个插件还是用不了
![image](https://github.com/halo-sigs/plugin-oauth2/assets/45005201/42244f48-7ccb-4a8d-97a7-1dcaafc9aec6)
![image](https://github.com/halo-sigs/plugin-oauth2/assets/45005201/967f222e-2d1c-4e26-841b-ca07fd50a253)

**Comment by ruibaby** [comment]
OAuth2 插件所需 Halo 的最低版本为 2.4.0，你需要升级 Halo。

/kind support

**Comment by AbsoluteZeroKing** [comment]
我已经升级了2.4了呀，难道升级会失败吗，用的是docker你官网的方式运行的升级

**Comment by AbsoluteZeroKing** [comment]
另外挺想问一下现在怎么看自己halo版本是多少呀，之前可以直接看到的

**Comment by AbsoluteZeroKing** [comment]
sorry，我确认了一下应该是我没升级成功，重装一下就好了
