### ISSUE TITLE
回调地址问题

### ISSUE THREAD

**Issue by Dacong-wu** [halo-sigs/plugin-oauth2#35]
1.为什么回调地址要设置http才可以使用，使用http是否会有安全性问题？
2.为什么使用github登录成功后，退出登录后，再次点击登录后直接就进页面了？

**Comment by JohnNiang** [comment]
1. 如果你使用的 CDN 并且回源协议选择的 HTTP，那么回调地址只能使用 HTTP 协议。因为插件在构建回调地址的时候，会自动获取当前请求的协议进行拼接。这一点后续我们看有没有可能直接调用配置好的 `halo.external-url`。
2. 这个问题在新版中已经修复。

**Comment by JohnNiang** [comment]
/triage duplicate

Supersedes by <https://github.com/halo-sigs/plugin-oauth2/issues/73>.

/close
