### ISSUE TITLE
套cdn之后 无法gitee  和 github登陆

### ISSUE THREAD

**Issue by wxyShine** [halo-sigs/plugin-oauth2#38]
![image](https://github.com/halo-sigs/plugin-oauth2/assets/42802152/18c5fe4e-3dc1-4073-ae6a-8445314326a9)

地址:  https://www.wxy97.com

**Comment by JohnNiang** [comment]
Hi @wxyShine ，请问是如何解决的呢？

/kind support

**Comment by wxyShine** [comment]
> Hi @wxyShine ，请问是如何解决的呢？
> 
> /kind support /实物支持

![image](https://github.com/halo-sigs/plugin-oauth2/assets/42802152/ce3b0a3e-e296-4c7b-9b99-c3395fcae1a0)
![image](https://github.com/halo-sigs/plugin-oauth2/assets/42802152/c0b67ca8-3d01-40cc-9db8-a48a19564fe3)
在又拍cdn配置里面: 重定向关掉了  加了个不缓存路径，不知道具体是那个生效的
