### ISSUE TITLE
新增其它登录方式

### ISSUE THREAD

**Issue by wx-1124** [halo-sigs/plugin-oauth2#47]
后续考虑新增其它登陆方式吗，比如像微信QQ之类的

**Comment by liheji** [comment]
不知道是否会接入 [JustAuth](https://www.justauth.cn/)，可以实现国内绝大部分的OAuth

**Comment by lhDream** [comment]
> 后续考虑新增其它登陆方式吗，比如像微信QQ之类的

@wx-1124 微信QQ已经有一个收费版的了,估计不会出了

**Comment by JohnNiang** [comment]
> > 后续考虑新增其它登陆方式吗，比如像微信QQ之类的
> 
> [@wx-1124](https://github.com/wx-1124) 微信QQ已经有一个收费版的了,估计不会出了

只要支持 OAuth2 认证协议，我们后续都可以支持，这和另外一个插件并不冲突。

**Comment by lhDream** [comment]
@JohnNiang 我加了 Linux Do的配置,可以合进来吗

**Comment by JohnNiang** [comment]
Hi @lhDream ，后续会尝试在 Console 侧添加新增 AuthProvider 的功能。届时内置的 GitHub 和 Gitee 都有可能会移除掉。所以我建议暂时不添加新的配置。

**Comment by JohnNiang** [comment]
Closes in favor of <https://github.com/halo-sigs/plugin-oauth2/issues/23>.

/triage duplicate
/close
