### ISSUE TITLE
OAuth 2 登录失败

### ISSUE THREAD

**Issue by steveji2021** [halo-sigs/plugin-oauth2#50]
你好，

我在个人博客（https://rsps.myds.me:444，Halo 2.17.1）上安装了 OAuth 2（1.2.0），按照ReadMe正确创建了Gitee应用并配置了client_id和secret，截图如下：

![IMG_0009](https://github.com/halo-sigs/plugin-oauth2/assets/88028845/b87d775e-2458-4c74-8ff1-47e5c9a04925)
![IMG_0010](https://github.com/halo-sigs/plugin-oauth2/assets/88028845/aa683d01-f1af-4ead-abc9-9ed242d52fa9)

但在尝试绑定账号时，提示回调地址无效：

![IMG_0011](https://github.com/halo-sigs/plugin-oauth2/assets/88028845/be023163-fe10-46dc-b39a-7779a1ea5266)

附带日志如下：
[halo-log-2024-07-10 15_49.log](https://github.com/user-attachments/files/16157682/halo-log-2024-07-10.15_49.log)

麻烦查看一下，谢谢

=============================

PS：我似乎发现redirect_uri参数中端口号丢了。手动加上后正常弹出请求页面，但点击同意授权后页面重定向到”/login?error”，登录仍不成功。

**Comment by ruibaby** [comment]
你可以尝试一下把回调地址的协议改为 http://，因为有类似的反馈，用 https 协议不行，但是 http 可以。

**Comment by steveji2021** [comment]
尝试了，未成功

**Comment by JohnNiang** [comment]
![](https://private-user-images.githubusercontent.com/88028845/347318067-b87d775e-2458-4c74-8ff1-47e5c9a04925.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODE1MjQsIm5iZiI6MTcyOTU4MTIyNCwicGF0aCI6Ii84ODAyODg0NS8zNDczMTgwNjctYjg3ZDc3NWUtMjQ1OC00Yzc0LThmZjEtNDdlNWM5YTA0OTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MGQwMTNiYjZkZTNkNGYzM2I2ZjA3NGI0MDhkM2VkYmFkMzAwMTViOGQzYzRiMmRhYWEyNGNkMjM3MmIxY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qrPGugm1do6KJ6xu-Y9Z5hPFWhGC3z3AyudNNgTgMs0)

这里填写的回调地址设置成小写试试。

**Comment by steveji2021** [comment]
可用

**Comment by steveji2021** [comment]
已成功
