### ISSUE TITLE
登录跳转地址错误

### ISSUE THREAD

**Issue by QingFeng-awa** [halo-sigs/plugin-oauth2#67]
### 问题描述
我退出登录后从网站首页的登录入口重新登录,使用第三方Gitee登录后跳转到了`/console/login`。
显然这应该是个没适配完的问题,但是我不知道是不是因为我在1小时内绑定Gitee Cookie还没过期,跳转后登录却成功了……

### 环境信息
- 外部访问地址: https://support.xtreme.net.cn
- 启动时间: 2024-10-15 23:11
- 版本: 2.20.3
- 构建时间: 2024-10-15 17:29
- Git Commit: 3a3e0e8
- Java: IBM Semeru Runtime Open Edition / 21.0.4+7-LTS
- 数据库: MySQL Community Server - GPL / 8.4.2
- 操作系统: Linux / 6.1.0-25-amd64
- 已激活主题: [Ocean 1.4.2](https://github.com/f2ccloud/theme-ocean.git)
- 已启动插件:
  - [Trailing Slash 1.0.0](https://github.com/halo-sigs/plugin-trailing-slash)
  - [编辑器超链接卡片 1.0.3](https://github.com/halo-sigs/plugin-editor-hyperlink-card)
  - [站点推送插件 1.5.2](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [OAuth2 认证 1.4.1](https://github.com/halo-sigs/plugin-oauth2)
  - [搜索组件 1.6.2](https://github.com/halo-dev/plugin-search-widget)
  - [Sitemap 1.1.2](https://github.com/halo-dev/plugin-sitemap)
  - [评论组件 2.5.0](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场 1.5.1](https://www.halo.run/store/apps/app-VYJbF)

**Comment by JohnNiang** [comment]
Hi @QingFeng-awa thank you for reaching out here!

登录后跳转至 /console/login 的原因是主题页面的右上角跳转链接是 /console/login，Halo 2.20 对 /console 路径做了认证，并在跳转至 /login 之前保存了 /console/login，并在登录成功之后进行跳转。

所以这里需要对应的主题对 Halo 2.20 做好适配才能正确跳转。
