### ISSUE TITLE
github配置好了ID和Secret，登录时提示Invalid Redirect URI

### ISSUE THREAD

**Issue by chengpei** [halo-sigs/plugin-oauth2#72]
github配置好了ID和Secret，登录时提示Invalid Redirect URI，redirect_uri是一个docker的内网地址，没有用我的域名外网地址，导致跳到github报错“Invalid Redirect URI”

**Comment by JohnNiang** [comment]
这里的 redirect URI 地址必须填写你的外部访问地址。因为在跳转过程中会获取当前请求的外部访问地址来构建 redirect URI。

/kind support

**Comment by JohnNiang** [comment]
不好意思，我刚刚理解错误了。

根据描述，应该是你的反向代理工具没有正确代理 Host 头。可能的解决方案：
- <https://github.com/halo-sigs/plugin-oauth2/issues/70#issuecomment-2437458967>

**Comment by chengpei** [comment]
感谢，是代理配置的问题

**Comment by JohnNiang** [comment]
> 感谢，是代理配置的问题

建议尝试一下 [1.4.2](https://github.com/halo-sigs/plugin-oauth2/releases/tag/v1.4.2)，这个版本修复了这个问题。即使代理没有正确配置，也能够正常解析了，不过前提是你配置了外部访问地址。
