### ISSUE TITLE
求助：回调地址问题

### ISSUE THREAD

**Issue by holwell** [halo-sigs/plugin-oauth2#75]
情况：
* 域名备案还未申请下来，也就是没有域名，只有 ip 地址的情况下测试。
* halo 搭建在 8090 端口，使用的 Nginx Proxy Manager 反向代理到 80 端口，8090 端口未开放。
问题：
* 如果把 github 的回调地址填成不带端口的 ip 回调地址时，github 登录授权页会提示“重定向连接没有关联应用”
![Image](https://github.com/user-attachments/assets/1656916a-dbb1-4e23-9b22-ad0aa5467a0e)
* 如果把 github 回调地址填成带端口的回调地址时，则会跳转到未开放的 8090 端口地址。
这个问题是没有域名解析导致的吗，还是需要配置什么东西，感谢！

**Comment by ruibaby** [comment]
使用最新版本插件，以及正确设置 Halo 的外部访问地址。

**Comment by holwell** [comment]
> 使用最新版本插件，以及正确设置 Halo 的外部访问地址。

非常感谢，解决了，确实是 Halo 部署的配置文件中的外部访问地址问题，我填成带端口的了。
