### ISSUE TITLE
新特性建议：自定义回调地址

### ISSUE THREAD

**Issue by holwell** [halo-sigs/plugin-oauth2#76]
* 目前情况
OAuth2 请求 API  `<SITE_URL> /oauth2/authorization/github` 不能携带任何参数，它会重定向到带有参数的 `https://github.com/login/oauth/authorize?response_type=&client_id=&scope=&state=&redirect_uri=http://<SITE_URL>/login/oauth2/code/github` 地址，然后完成 github 授权后回调 `http://<SITE_URL>/login/oauth2/code/github` 地址。

* 期望特性
能让 `<SITE_URL> /oauth2/authorization/github` 可以携带 `redirect_uri` 参数，在重定向的时候把 `redirect_uri` 参数传递给  `https://github.com/login/oauth/authorize`，然后完成授权就可以回调到指定地址了。
同时，由于 github 回调地址限制必须是[子路由](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#redirect-urls)，建议把回调地址改成  `<SITE_URL>` 而不是  `<SITE_URL>/login/oauth2/code/github`，否则自定义重定向将失去意义。

* 应用场景
文章评论区使用 OAuth2 登录能回调到文章页，类似这样的评论区：
![Image](https://github.com/user-attachments/assets/3e7c0ec3-5b5c-494f-bb3f-a6cdc659fe7d)
当然，这需要搭配自动注册功能。否则，当用户未注册情况下，自定义回调的地址是文章页而不是  `http://<SITE_URL>/login/oauth2/code/github` 注册验证页也会很奇怪。但无论如何，这绝对是一个好的、自由度更高的设计，不会与现在的需求冲突。

**Comment by JohnNiang** [comment]
Hi @holwell, thank you for reaching out here!

这里的的回调地址来自于 OAuth2 Authorization Code 授权流程，详情请参考 <https://datatracker.ietf.org/doc/html/rfc6749#autoid-35>。主要用于接收 GitHub 传递的 code，并获取到 Access Token 来访问 GitHub 部分资源。关于登录成功之后的跳转地址，我们已经在 Halo 核心中实现了。例如：

1. 在未登录情况下访问：`/login?redirect_uri=/xyz`，那么就会在登录成功后跳转到 `/xyz` 页面。
2. 在未登录情况下访问：`/uc`，则会自动跳转到 `/login` 页面，通过 OAuth2 登录之后，会自动跳转到 `/uc`。

**Comment by holwell** [comment]
> Hi [@holwell](https://github.com/holwell), thank you for reaching out here!
> 
> 这里的的回调地址来自于 OAuth2 Authorization Code 授权流程，详情请参考 https://datatracker.ietf.org/doc/html/rfc6749#autoid-35。主要用于接收 GitHub 传递的 code，并获取到 Access Token 来访问 GitHub 部分资源。关于登录成功之后的跳转地址，我们已经在 Halo 核心中实现了。例如：
> 
> 1. 在未登录情况下访问：`/login?redirect_uri=/xyz`，那么就会在登录成功后跳转到 `/xyz` 页面。
> 2. 在未登录情况下访问：`/uc`，则会自动跳转到 `/login` 页面，通过 OAuth2 登录之后，会自动跳转到 `/uc`。

非常感谢！学习了！
